DROP SCHEMA PUBLIC CASCADE;

CREATE TABLE Users (
  id INTEGER IDENTITY PRIMARY KEY,
  username VARCHAR(30),
  password VARCHAR(30)
);


CREATE CACHED TABLE Expense (
  id INTEGER IDENTITY PRIMARY KEY,
  amount double,
  date TIMESTAMP ,
  description VARCHAR(30),
  userId INTEGER NOT NULL;
);

ALTER TABLE Expense ADD FOREIGN KEY (userId) REFERENCES Users (id);